development:
  clients:
    default:
      database: hackdepot_development
      hosts:
        - mongo:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

production:
  clients:
    default:
      database: hackdepot_production
      hosts:
        - mongo:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
